In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [52]:
#filename = "/home/viviane/GravLens/Scraping/masterlens/masterlens_2.html"  # list with dfs from tables
filename = '/home/vivianemm/PycharmProjects/GravLens/Database/Scraping/masterlens/masterlens_1.html'
df_list = pd.read_html(filename)

In [53]:
# important dfs: 5,6,7,11,12,13,14,16,17,18,19,20,21
for i in df_list:
    print(i.columns.values)

[0]
[0 1 2 3]
[0 1 2 3 4 5]
[0]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1 2]
[0 1]
[0 1]
[0 1]
[0 1 2 3]
[0 1]
[0 1 2 3]
[0 1 2 3 4 5 6 7]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7 8]
[0 1]
[0 1]
[0 1 2 3 4 5 6 7 8]


In [66]:
df_list[12]

0                1                2           3
0        System Name  SDSS J0008-0004  Discovery Date:  2008-08-01
1  Alternate Name(s)              NaN              NaN         NaN

### Defining functions

In [4]:
def pick_table(df_list, key):
    for df in df_list:
        list_labels = list(df.columns.values)
        if any(isinstance(i, tuple) for i in list_labels):  # if labels is nested list
            labels = [item for t in list_labels for item in t]  # flatten
        else:
            labels = list_labels

        list_values = df.values.tolist()
        if any(isinstance(i, list) for i in list_values):  # if values is nested list
            values = [item for t in list_values for item in t]  # flatten
        else:
            values = list_values
              
        if key in values or key in labels:
            #df_list.remove(df)
            return df

In [5]:
from collections import defaultdict

def get_tables(soup, text=False):
    table_dict_list = []
    
    tables = soup.find_all('table')
    
    for table in tables:
        table_dict = defaultdict(list)
        
        
        headers = [header.get_text() for header in table.find_all('th')]
        
        if len(headers) == 0:
            pass
        else:
            
            if text:
                rows = [[data.get_text() for data in col.find_all('td')] for col in table.find_all('tr')]
            else:
                rows = [[data for data in col.find_all('td')] for col in table.find_all('tr')]

            for row in rows:
                columns_id = 0
                for data in row:
                    column_name = headers[columns_id]

                    table_dict[column_name].append(data)
                    columns_id += 1

            table_dict_list.append(table_dict)
        
    return table_dict_list

In [6]:
def drop_nans(df):
    df.dropna(axis=0, how='all', inplace=True)
    df.dropna(axis=1, how='all', inplace=True)
    return None

In [7]:
def split_col(df, old_new_list):  # old_new_list = [[oldname, newname], ...]
    for pair in old_new_list:
        if pair[0] in df.columns and type(list(df[pair[0]])[0]) == str and "±" in list(df[pair[0]])[0]:
            df[[pair[1], pair[1] + '_err']] = df[pair[0]].str.split("±", n = 1, expand = True)
            df.drop(pair[0], axis=1, inplace=True)
        else:
            pass
    return None

In [8]:
def get_table_links(table):
    href_list = []
    
    if isinstance(table, list):
        for row in table:
            href = row.find('a')['href']
            href_list.append(href)
    else:
        href_tags = table.find_all("a")
        for tag in href_tags:
            href = tag.get('href')
            href_list.append(href)
    return href_list

In [33]:
def save(df, filename, i=False):
    if len(df) > 0:
        #df.to_csv("/home/viviane/GravLens/Scraping/results/" + filename, index = i)
        df.to_csv('/home/vivianemm/PycharmProjects/GravLens/Database/Scraping/results/' + filename, index = i)
        
    return None

### System table
### (5, 6, 7, 11, 12, 20)

In [71]:
def system(df_list):
    # joining 5,6,7,11
    frames =[pick_table(df_list, 'Discovery'), pick_table(df_list, 'Lens Kind'), 
             pick_table(df_list,'Lens Grade'), pick_table(df_list, 'Description')]
    result_df = pd.concat(frames)
    result_df.reset_index(drop=True, inplace=True)
    system_df = result_df.drop(columns=0).T
    system_df.columns = list(result_df[0])
    
    
    # Splitting value ± error columns
    split_col(system_df, [['Einstein_R ["]','Einstein_R'], ['z_Lens', 'z_lens'], ['z_Source(s)', 'z_source'],
                          ['Stellar velocity disp', 'Stellar_v_disp']])
    
    # adding other 2 tables
    date_df = pick_table(df_list, 'Discovery Date:')
    n_df = pick_table(df_list, 'Number of Source Plane Images')
    
    system_df['Discovery Date'] = date_df[3][0]
    system_df['Name'] = date_df[1][0]
    system_df['N Images'] = n_df[1][0]
    system_df['Alternate Names'] = date_df[1][1]
    
    drop_nans(system_df)
    return system_df

In [73]:
system_df = system(df_list)
system_df

Discovery Lens Kind Lens Grade Einstein_R quality z_Lens quality  \
1     SLACS   GAL-GAL          A          SIE model  spectroscopic   

  z_Source quality                                        Description  \
1    spectroscopic  Luminous red galaxy lensing three background o...   

  Einstein_R Einstein_R_err   z_lens z_lens_err z_source z_source_err  \
1      1.16            0.02  0.4400      0.0001   1.192         0.001   

  Stellar_v_disp Stellar_v_disp_err Discovery Date             Name  N Images  
1           232                  39     2008-08-01  SDSS J0008-0004         3

### Coordinates table (13)

In [23]:
def coordinates(df_list):
    coords_df = pick_table(df_list, 'Coordinates:') #.drop(2, axis=1)  # Manual coordinates
    coords_df.drop(2, axis=1, inplace=True)    
    coords_df = coords_df.set_index(0).T
    coords_df['Coordinates:'] = 'Manual'
    coords_df = coords_df.set_index('Coordinates:')

    return coords_df

In [24]:
coordinates(df_list)

KeyError: '[2] not found in axis'

### External links


In [958]:
def external(df_list, filename):    
    #external_df.columns = [''] * len(external_df.columns)
    #external_df.drop('External Links:.1', axis=1, inplace=True)
    
    soup = BeautifulSoup(open(filename), "lxml")
    external_df = pick_table(df_list, 'External Links:')
    for table in soup.find_all('table'):
            
        if table.th is not None and table.th.text == 'External Links:':
            refs = get_table_links(table)
        else:
            pass
            
            #if external_df is not None:
    external_df.columns = ['database', 'link']
    external_df = external_df.set_index('database')
    drop_nans(external_df)
    external_df['links'] = refs
    external_df.drop('link', axis=1, inplace=True)
    
    return external_df

### Flux table (SDSS 16, HST 17)

In [978]:
########### outros filtrosssss CFHTLS
def sdss(df_list):
    df = pick_table(df_list,'Filter')
    if df is not None and'SDSS' in df.columns.values:
        sdss_df = df.set_index('Band')
        sdss_df = sdss_df.drop(columns=['Unnamed: 1'])
    else:
        sdss_df = pd.DataFrame()

    return sdss_df


def hst(df_list):
    hst_df = pick_table(df_list,'HST')

    if hst_df is not None:
        hst_df = hst_df.drop(columns=['Unnamed: 1'])
        hst_df = hst_df.set_index('Band')
    else:
        hst_df = pd.DataFrame()
    return hst_df


def flux(df_list):
    sdss_df = sdss(df_list)
    hst_df = hst(df_list)

    flux_df = pd.concat([sdss_df, hst_df])
    #flux_df['release'] = list(sdss_df['SDSS']) + list(hst_df['HST'])
    #flux_df = flux_df.drop(columns=['SDSS','HST'])

    drop_nans(flux_df)
    split_col(flux_df, [['Lens Magnitude', 'lens_mag'], ['Flux [nmaggie]', 'Flux (nmaggie)'],
                    ['Reff [″]', "ref (arcsec)"], ['axis ratio (AB)', 'axis_ratio (AB)'],
                    ['PA [° E of N]','PA (deg)']])
    return flux_df

In [966]:
flux(df_list)    #CFHTLS

Empty DataFrame
Columns: []
Index: []

### Redshift table (18, 19)

In [899]:
def redshift(df_list):

    z_lens_df = pick_table(df_list, 'Lens Plane Images:')
    if z_lens_df is not None:
        z_lens_df = z_lens_df['Lens Plane Images:']
        #z_lens_df = z_lens_df.set_index('No.')
    else:
        z_lens_df = pd.DataFrame()

    z_source_df = pick_table(df_list, 'Source Plane Images:')
    if z_source_df is not None:
        z_source_df = z_source_df['Source Plane Images:']
        #z_source_df = z_source_df.set_index('No.')
    else:
        z_source_df = pd.DataFrame()

    z_df = pd.concat([z_lens_df, z_source_df], keys=['Lens', 'Source'])
    drop_nans(z_df)

    return z_df

In [900]:
z_lens_df = pick_table(df_list, 'Lens Plane Images:')
z_lens_df

Lens Plane Images:                             
                 No. Label     z   z_err Flux Mag
0                  1   NaN  0.44  0.0001  NaN NaN

In [901]:
redshift(df_list)

/home/viviane/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.



No.      z   z_err
Lens   0    1  0.440  0.0001
Source 0    1  1.192  0.0010
       1    2  1.192  0.0010
       2    3  1.192  0.0010

### Time delay table (21)

In [902]:
def time(df_list):
    time_df = pick_table(df_list, 'Time Delays:')

    if time_df is not None:
        times = list(time_df['Time Delays:']['Time Delay (days)'])
    #print(times)
        if np.isnan(times).all():
            time_df = None

    return time_df

In [903]:
d = time(df_list)
type(d)

NoneType

### References table (14)

In [904]:
def refs(filename, df_list):
    soup = BeautifulSoup(open(filename), "html.parser")

    for table in soup.find_all('table'):
    # links = [np.where(tag.has_attr('href'),tag.get('href'),"no link") for tag in tb.find_all('a')]

        links = get_table_links(table)
        #print(links)

        if len(links) >= 2 and 'citation' in links[1]:
            papers = links[1::2]

    ref_df = pick_table(df_list, 'Discovery\xa0Paper')
    ref_df = ref_df.drop('Unnamed: 0', axis=1)

    ref_df['Links'] = papers
    ref_df.columns = ['Author', 'Title', 'Discovery', 'Links']
    return ref_df

In [905]:
refs(filename, df_list)

Author  \
0  Cardone et al. 2011 [MNRAS416(2011)1822]   
1      Auger et al. 2009 [ApJ705(2009)1099]   
2     Newton et al. 2009 [ApJ696(2009)1125]   
3      Grillo et al. 2009 [A&A501(2009)461]   
4        Treu et al. 2009 [ApJ690(2009)670]   
5      Bolton et al. 2008 [ApJ682(2008)964]   

                                               Title        Discovery  \
0  Secondary infall model and dark matter scaling...              NaN   
1  The Sloan Lens ACS Survey. IX. Colors, Lensing...              NaN   
2  Enhanced Lensing Rate by Clustering of Massive...              NaN   
3  Photometric mass and mass decomposition in ear...              NaN   
4  The SLACS Survey. VIII. The Relation between E...              NaN   
5  The Sloan Lens ACS Survey. V. The Full ACS Str...  Discovery Paper   

                                               Links  
0  http://admin.masterlens.org/citation.php?refer...  
1  http://admin.masterlens.org/citation.php?refer...  
2  http://admin.masterlens.org/citation.php?refer...  
3  http://admin.masterlens.org/citation.php?refer...  
4  http://admin.masterlens.org/citation.php?refer...  
5  http://admin.masterlens.org/citation.php?refer...

### Main code

In [27]:
for lens_n in range(1,51):
    filename = "/home/viviane/GravLens/Scraping/masterlens/masterlens_" + str(lens_n) + ".html"
    #filename = '/home/vivianemm/PycharmProjects/GravLens/Scraping/masterlens/masterlens_1.html'
    df_list = pd.read_html(filename)

    system_df = system(df_list)
    coords_df = coordinates(df_list)
    flux_df = flux(df_list)
    z_df = redshift(df_list)
    ref_df = refs(filename, df_list)
    external_df = external(df_list, filename)
    time_df = time(df_list)
    
    save(system_df, 'system_{}.csv'.format(lens_n))
    save(coords_df, 'coordinates_{}.csv'.format(lens_n))
    save(flux_df, 'flux_{}.csv'.format(lens_n), i=True)
    save(z_df, 'redshift_{}.csv'.format(lens_n), i=True)
    save(ref_df, 'references_{}.csv'.format(lens_n))
    save(external_df, 'external_{}.csv'.format(lens_n),i=True)
    
    print(lens_n)

ValueError: No tables found

In [1029]:
pd.read_csv('results/coordinates_50.csv')

RA Hrs  RA Mins  RA Secs      RA [°]  Dec Degrees  Dec Arcmin  Dec Arcsec  \
0      10        4       34  151.143143           41          12        42.8   

     Dec [°]  
0  41.212109

### Castles


In [83]:
filename_c = '/home/vivianemm/PycharmProjects/GravLens/Database/castles.html'
df_list = pd.read_html(filename_c)

In [84]:
castles = df_list[1]
castles.rename(columns=castles.iloc[0], inplace=True)
castles.drop(['#', 'Image', 'G'], axis=1, inplace=True)
castles.drop([0], inplace=True)
castles = castles.set_index(['Lens Name'])
# split sigma
castles

zs         zl    RA (J2000)   Dec (J2000) E(B-V)  \
Lens Name                                                                      
Q0047-2808                3.60       0.48   00:49:41.89   -27:52:25.7  0.016   
HE0047-1756               1.66       0.41   00:50:27.83    -17:40:8.8  0.022   
HST01247+0352              NaN        NaN    01:24:44.4     +03:52:00  0.029   
HST01248+0351              NaN        NaN    01:24:45.6     +03:51:06  0.029   
B0128+437                3.124        NaN  01:31:13.405  +43:58:13.14  0.082   
PMNJ0134-0931            2.216       0.77   01:34:35.67   -09:31:02.9  0.031   
Q0142-100                 2.72       0.49    01:45:16.5     -09:45:17  0.031   
QJ0158-4325               1.29      0.317   01:58:41.44  -43:25:04.20  0.015   
B0218+357                 0.96       0.68  02:21:05.483  +35:56:13.78  0.068   
HE0230-2130              2.162       0.52    02:32:33.1     -21:17:26  0.022   
SDSS0246-0825             1.68        NaN   02:46:34.11   -08:25:36.2  0.026   
CFRS03.1077              2.941      0.938    03:02:30.9   +00:06:02.1  0.098   
J0332-2756                 NaN      0.617   03:32:38.22   -27:56:52.9  0.008   
MG0414+0534               2.64       0.96   04:14:37.73   +05:34:44.3  0.303   
HE0435-1223              1.689       0.46    04:38:14.9   -12:17:14.4  0.059   
B0445+123                  NaN      0.557   04:48:21.99  +12:27:55.41  0.431   
HE0512-3329               1.57     (0.93)   05:14:10.78  -33:26:22.50  0.024   
B0631+519                  NaN  0.09/0.62   06:35:12.31   +51:57:01.8  0.092   
B0712+472                 1.34       0.41   07:16:03.58   +47:08:50.0  0.113   
B0739+366                  NaN        NaN    07:42:51.2   +36:34:43.7  0.076   
SDSS0746+4403             2.00        NaN   07:46:53.03   +44:03:51.3    NaN   
MG0751+2716               3.20       0.35   07:51:41.46  +27:16:31.35  0.034   
SDSS0806+2006            1.540      0.573   08:06:23.70   +20:06:31.9  0.034   
HS0810+2554               1.50        NaN    08:13:31.3   +25:45:03.2  0.040   
HS0818+1227              3.115       0.39    08:21:39.1     +12:17:29  0.031   
APM08279+5255             3.87        NaN   08:31:41.59   +52:45:17.0  0.050   
B0850+054           1.14/3.93?       0.59   08:52:53.58   +05:15:15.3  0.062   
SDSS0903+5028            3.605      0.388   09:03:34.92   +50:28:19.2  0.025   
RXJ0911+0551              2.80       0.77   09:11:27.50   +05:50:52.0  0.045   
SBS0909+523               1.38       0.83   09:13:01.05  +52:59:28.83  0.015   
...                        ...        ...           ...           ...    ...   
SBS1520+530               1.86       0.72   15:21:44.83   +52:54:48.6  0.016   
HST15433+5352            2.092      0.497    15:43:20.9     +53:51:52  0.012   
MG1549+3047               1.17       0.11   15:49:12.37   +30:47:16.6  0.029   
B1555+375                  NaN        NaN   15:57:11.93   +37:21:35.9  0.022   
B1600+434                 1.59       0.41   16:01:40.45   +43:16:47.8  0.013   
B1608+656                 1.39       0.63   16:09:13.96   +65:32:29.0  0.031   
HST16302+8230              NaN        NaN    16:30:12.9     +82:29:59  0.087   
HST16309+8230              NaN        NaN    16:30:52.7     +82:30:12  0.087   
PMNJ1632-0033            3.424        NaN   16:32:57.68   -00:33:21.1  0.098   
FBQ1633+3134              1.52        NaN   16:33:48.99  +31:34:11.90  0.030   
SDSS1650+4251             1.54        NaN   16:50:43.44   +42:51:45.0  0.016   
MG1654+1346               1.74       0.25   16:54:41.83   +13:46:22.0  0.061   
HST18078+4600              NaN        NaN    18:07:46.7     +45:59:56  0.037   
PKS1830-211               2.51       0.89   18:33:39.94   -21:03:39.7  0.464   
PMNJ1838-3427             2.78        NaN    18:38:28.5   -34:27:41.6  0.125   
B1933+503                 2.63       0.76   19:34:30.95   +50:25:23.6  0.095   
B1938+666                2.059      0.881   19:38:25.19   +66:48:52.2  0.121   
PMNJ2004-1349              N

In [85]:
castles.to_csv("castles.csv")